name: Build and Deploy to Firebase Hosting

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main  # Adjust this if your deploy branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from your GitHub repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (this ensures we can use npm for build steps)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust the Node.js version if needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run the build script (you should replace 'npm run build' with your actual build script)
      - name: Run Build Script
        run: npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "henok-assalif"  # Your Firebase project ID
